version: '3.8'
services:
  backend:
    build: ./backend
    ports: ["8000:8000"]
    env_file: .env
    depends_on:
      - db
      - kafka
      - minio
      - zookeeper
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
  frontend:
    build: ./frontend
    ports: ["5173:5173"]
    env_file: .env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/.env:/app/.env
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
  kafka:
    image: 'bitnami/kafka:3.3'
    user: root
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka:/bitnami/kafka
    depends_on:
      - zookeeper 

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports: ["9000:9000", "9001:9001"]
    env_file: .env
    volumes:
      - minio_data:/data
  db:
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports: ["5432:5432"]
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
  minio_data:
  kafka: {}

